library(xml2)

test_that("structure is intact", {
  raw <- page_navbar("title", "https://example.com")
  expect_true(is.character(raw) && !any(raw == ""))
  html <- read_html(paste(raw, collapse = ""))
  children <- xml_child(html)
  expect_true(xml_length(children) == 1)
  children <- xml_child(children)
  expect_true(xml_length(children) == 1)
  children <- xml_child(children)
  expect_true(xml_length(children) == 2)
  expect_true(xml_length(xml_child(children)) == 1)
  expect_true(xml_length(xml_child(children, 2)) == 0)
})
